### ISSUE TITLE
This control is brilliant.

### ISSUE THREAD

**Issue by daviddelmonte** [badalpub1991/BASReport#1]
Thanks so much. Any chance of a Swift 5 update to the CocoaPods version. Right now, I am using updated source files.

**Comment by badalpub1991** [comment]
Thank you . Thanks a lot. Hi. Yes i noticed that. Sorry but i am busy in my current schedule. I will update it.

**Comment by badalpub1991** [comment]
Hi, new version is updated to swift5. please check it. Thank you.
