### ISSUE TITLE
Spelling of Delegate

### ISSUE THREAD

**Issue by daviddelmonte** [badalpub1991/BASReport#2]
Hi, throughout the control, you have "Delegate" spelled as "Deleate". Would you please change that.

Thanks again

**Comment by badalpub1991** [comment]
Hi. Yes i noticed that. Sorry but i am busy in my current schedule. I will update it. If you have time Can you do it. ?

**Comment by badalpub1991** [comment]
Hi , your issue has been fixed. please check it.
